version: "3.1"

services:
  users:
    image: amalthea-users:1.0-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://amalthea_users_db:5432/amalthea_users
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - amalthea_users_db

  wallets:
    image: amalthea-wallets:1.0-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://amalthea_wallets_db:5434/amalthea_wallets
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - amalthea_wallets_db

  currency-rates:
    image: amalthea-currency-rates:1.0-SNAPSHOT
    ports:
      - "8081:8081"

  amalthea_users_db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=amalthea_users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    command: postgres -p 5432

  amalthea_wallets_db:
    image: postgres:13.1
    environment:
      - POSTGRES_DB=amalthea_wallets
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5434"
    restart: always
    command: postgres -p 5434
